### ISSUE TITLE
Fix : SRS Belgesi Kullanıcı Arayüzleri

### ISSUE THREAD

**Issue by onurergun** [onurergun/BBM487-20142-1#33]
Referans olarak alınan IEEE 830-1998 Belgesine göre hazırlanmış olan SRS belgesinde, kullanıcı arayüzleri bölümünün olmadığının yapılan incelemeler sonucunda tespit edilmesinin ardından SRS belgesine bu bölümün eklenmesi

**Comment by kursatd** [comment]
SRS belgesinde bulunmayam arayüzler Yazılım Tasarım Belgesin SDD'de verilmiştir.

**Comment by onurergun** [comment]
Hatanın giderildiğini onaylanmıştır.
