### ISSUE TITLE
Fix : SRS Belgesi Veri Ortamı

### ISSUE THREAD

**Issue by onurergun** [onurergun/BBM487-20142-1#34]
İnceleme sonucu tespit edilen SRS belgesindeki "veri ortamı" bilgisi eksikliğinin giderilmesi

**Comment by kursatd** [comment]
SRS belgesine veri ortamıyla ilgili gerekli bilgiler eklenmiştir.

**Comment by onurergun** [comment]
SRS Belgesinin uygun şekilde güncellendiği onaylanmıştır.
