### ISSUE TITLE
Eşleşilen Grup İncelemesi: SDD Belgesi

### ISSUE THREAD

**Issue by BegumCitamak** [onurergun/BBM487-20142-1#38]
Yazılım tasarım belgesi hata kontrol listesinden yararlanarak yapılan SDD Belgesi incelemeleri sonucunda belirlenen hatalar şunlardır:

1. Tasarım belgesinde yer alan Sequence diagramlar yeterli sayıdadır ancak bu diagramlara ait kısa bilgilerin raporda yer almadığı gözlemlenmiştir.

2. Tasarım Belgesine bağlı test case’lerin sayısı yetersizdir.

3. IEEE  SDD belgesi standartlarına uyulmayarak veri sözlüğü bölümü belgede yer almamaktadır.

4. IEEE  SDD belgesi standartlarına uyulmayarak requirement matrix bölümü belgede yer almamaktadır.

**Comment by onurergun** [comment]
Tespit edilen hatalar Grup 4 Yöneticisine iletilmiştir.
