### ISSUE TITLE
Eşleşilen grup incelemesi : SRS Belgesi

### ISSUE THREAD

**Issue by kursatd** [onurergun/BBM487-20142-1#39]
Eşleşilen grubun yazılım gereksinim belgesinde hata kontrol listesinden yararlanılarak SRS belgesi incelemesi sonucunda ortaya çıkan hatalar şunlardır:

1.	Class Diagramında kullanıcılara ait bazı özelliklerin eksik girildiği gözlemlenmiştir. Ayrıca class diagramında belgeyi okuyan bir kişi için açıklamalar olmadığı için açıklama metninin eklenmesi uygun görülmüştür.

2.	Veri ortamı yetersiz şekilde tanımlanmıştır.
Sistem gereksinim belgesinde sistemin veri ortamı yetersiz şekilde tanımlanmış ve veri ortamı hakkında gerekli olan detaylı bilgileri içermemektedir.

3.	IEEE SRS Belgesi standartlarına uyulmamıştır.

4.	Sistemdeki tasarım ve implementasyon kısıtları yetersiz şekilde tanımlanmış veya yoktur.

**Comment by onurergun** [comment]
Yapılan inceleme sonucu tespit edilen hatalar Grup 4 Proje Yöneticisine iletilmiştir.
