### ISSUE TITLE
İçsel inceleme: SRS Belgesi

### ISSUE THREAD

**Issue by kursatd** [onurergun/BBM487-20142-1#40]
Yazılım gereksinim belgesinde kontrol listesinden yararlanılarak yapılan incelemeler sonucunda SRS belgesinde ortaya çıkan hatalar şunlardır:

IEEE 830-1998 belgesinde bulunan bölümlerden bazılarını içermemektedir.
- SRS belgesi IEEE 830-1998 standardına göre içermesi gereken kullanıcı arayüzlerini içermemektedir.

**Comment by onurergun** [comment]
Bulunan hatalar sonucunda @kursatd kullanıcına düzeltme yapılması için issue açılmıştır. #33
